name: mysite_dev
services:
  reverse-proxy:
    image: traefik:v3.5
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true" # Enable the Traefik API/Dashboard
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # only expose services with explicit traefik labels
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=web"
      # TLS
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_ACME_EMAIL}"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog=true"            # enable access logs
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
      # Web UI (enabled with --api.insecure=true)
      # - "8080:8080"
    networks:
      - web
      - backend
    volumes:
    # Traefik listens to docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/dashboard`)" # Dashboard route
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)" # Dashboard route
      - "traefik.http.routers.api.entrypoints=web"
      # - "traefik.http.routers.api.entrypoints=websecure"
      # - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=myauth" # Apply the authentication middleware
      # Define the Basic Auth Middleware
      - "traefik.http.middlewares.myauth.basicauth.users=${TRAEFIK_AUTH_USER}" # AUTH Dashboard
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/mysite-frontend/Dockerfile.prod
    environment:
      - LOG_REQUESTS=${LOG_REQUESTS}
      - DEBUG=${DEBUG}
    # (ensure app listens on 0.0.0.0:4000)
    networks:
      - web # So Traefik can reach it
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=${TRAEFIK_HTTP_RULE}"
      - "traefik.http.services.frontend.loadbalancer.server.port=4000"
      - "traefik.docker.network=web"
      - "traefik.http.routers.frontend.entrypoints=web,websecure" # remove websecure
      # - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1

  backend:
    build:
      context: .
      dockerfile: apps/mysite-backend/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    networks:
      - backend
      - database
      # - web
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=${TRAEFIK_HTTP_BACKEND_RULE}"
      - "traefik.docker.network=backend" # web before backend
      - "traefik.http.services.backend.loadbalancer.server.port=8200"
    restart: unless-stopped

  postgres:
    image: postgres:16.10-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}            # Ensure tools default to the right DB user
    secrets:
      - db-password
    ports:
      - "5555:5432"
    networks:
      - database
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # Use the intended DB user instead of defaulting to 'root'
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-$${POSTGRES_USER:-postgres}}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

secrets:
  db-password:
    file: ${POSTGRES_PASSWORD_FILE}

# Isolate database network
networks:
  web:
    driver: bridge
    name: web
  backend:
    driver: bridge
    name: backend
  database:
    driver: bridge
    name: database

volumes:
  letsencrypt:
  db-data:
