/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToolCall } from './toolCall';
import { Media } from './media';


export interface AssistantMessage { 
    messageType?: AssistantMessage.MessageTypeEnum;
    metadata?: { [key: string]: any; };
    toolCalls?: Array<ToolCall>;
    media?: Array<Media>;
    text?: string;
}
export namespace AssistantMessage {
    export const MessageTypeEnum = {
        User: 'USER',
        Assistant: 'ASSISTANT',
        System: 'SYSTEM',
        Tool: 'TOOL'
    } as const;
    export type MessageTypeEnum = typeof MessageTypeEnum[keyof typeof MessageTypeEnum];
}


