/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Blog post creation/update request
 */
export interface BlogPostRequest { 
    /**
     * Unique slug
     */
    slug?: string;
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Content
     */
    content?: string;
    /**
     * Publication date
     */
    publishedAt?: string;
    /**
     * Thumbnail URL
     */
    thumbnailUrl?: string;
    /**
     * Post type
     */
    type?: BlogPostRequest.TypeEnum;
    /**
     * External URL
     */
    externalUrl?: string;
    /**
     * Tags
     */
    tags?: Set<string>;
}
export namespace BlogPostRequest {
    export const TypeEnum = {
        Blog: 'BLOG',
        Youtube: 'YOUTUBE',
        External: 'EXTERNAL'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


