/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Blog post response
 */
export interface BlogPostResponse { 
    /**
     * ID
     */
    id?: string;
    /**
     * Slug
     */
    slug?: string;
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Content
     */
    content?: string;
    /**
     * Author ID
     */
    authorId?: string;
    /**
     * Author name
     */
    authorName?: string;
    /**
     * Publication date
     */
    publishedAt?: string;
    /**
     * Creation date
     */
    createdAt?: string;
    /**
     * Update date
     */
    updatedAt?: string;
    /**
     * Thumbnail URL
     */
    thumbnailUrl?: string;
    /**
     * Post type
     */
    type?: BlogPostResponse.TypeEnum;
    /**
     * External URL
     */
    externalUrl?: string;
    /**
     * Tags
     */
    tags?: Set<string>;
}
export namespace BlogPostResponse {
    export const TypeEnum = {
        Blog: 'BLOG',
        Youtube: 'YOUTUBE',
        External: 'EXTERNAL'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


