/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Generation } from './generation';
import { ChatResponseMetadata } from './chatResponseMetadata';


export interface ChatResponse { 
    result?: Generation;
    results?: Array<Generation>;
    metadata?: ChatResponseMetadata;
}

