/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RateLimit } from './rateLimit';
import { Usage } from './usage';


export interface ChatResponseMetadata { 
    id?: string;
    model?: string;
    rateLimit?: RateLimit;
    usage?: Usage;
    promptMetadata?: any | null;
    empty?: boolean;
}

