/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommentTreeItem { 
    id?: string;
    userId?: string;
    content?: string;
    createdAt?: string;
    updatedAt?: string;
    replyCount?: number;
    likeCount?: number;
}

