/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Comment response
 */
export interface CommentResponse { 
    /**
     * ID
     */
    id?: string;
    /**
     * User ID
     */
    userId?: string;
    /**
     * Content
     */
    content?: string;
    /**
     * Parent comment ID
     */
    parentCommentId?: string;
    /**
     * Replies
     */
    replies?: Array<any>;
    /**
     * Creation date
     */
    createdAt?: string;
    /**
     * Update date
     */
    updatedAt?: string;
}

