/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Like information
 */
export interface LikeResponse { 
    /**
     * Like count
     */
    likeCount?: number;
    /**
     * Is liked by user
     */
    isLiked?: boolean;
}

