/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MimeType } from './mimeType';


export interface Media { 
    id?: string;
    mimeType?: MimeType;
    data?: any | null;
    name?: string;
    dataAsByteArray?: string;
}

