/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Message { 
    messageType?: Message.MessageTypeEnum;
    text?: string;
    metadata?: { [key: string]: any; };
}
export namespace Message {
    export const MessageTypeEnum = {
        User: 'USER',
        Assistant: 'ASSISTANT',
        System: 'SYSTEM',
        Tool: 'TOOL'
    } as const;
    export type MessageTypeEnum = typeof MessageTypeEnum[keyof typeof MessageTypeEnum];
}


