/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { CommentTreeItem } from './commentTreeItem';
import { SortObject } from './sortObject';


export interface PageCommentTreeItem { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<CommentTreeItem>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

