/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { CommentResponse } from './commentResponse';
import { SortObject } from './sortObject';


export interface PageCommentResponse { 
    totalPages?: number;
    totalElements?: number;
    first?: boolean;
    size?: number;
    content?: Array<CommentResponse>;
    number?: number;
    sort?: SortObject;
    numberOfElements?: number;
    pageable?: PageableObject;
    last?: boolean;
    empty?: boolean;
}

