/**
 * MKopp.Dev Backend API
 *
 * Contact: michaeljg.kopp@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RateLimit { 
    tokensReset?: string;
    tokensLimit?: number;
    requestsLimit?: number;
    tokensRemaining?: number;
    requestsReset?: string;
    requestsRemaining?: number;
}

